---
- name: Print db hosts
  debug:
    var: groups['db']

- name: Print extracted IP addresses
  debug:
    var: groups['db'] | map('extract', hostvars, ['ansible_default_ipv4', 'address'])

- name: Print joined string
  debug:
    var: groups['db'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',')
