---

- hosts: all
  become: true
  tasks:
  - name: install apache2 and php Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"