---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: "Include variables"
      include_vars: "{{ item }}"
      with_first_found:
        - pjvars.yml"
     
    - name: Set IP facts
      set_fact:
        ip1: "{{ ips[0] }}"
        ip2: "{{ ips[1] }}"
        ip3: "{{ ips[2] }}"