---
#  - name: Print db hosts
#    debug:
#      var: groups['db'#]

#  - name: Print extracted IPs
#    debug:
#      var: groups['db'] | map('extract', hostvars, ['ansible_default_ipv4', 'address'])| sort | list
#  
#  - name: Print joined string
#    debug:
#      var: groups['db'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',')

#  - name: Print db hosts
#    debug:
#      var: groups['db']
#  
#  - name: Print first db host
#    debug:
#      var: groups['db'][0]
  
#  - name: Print ansible_default_ipv4 of first db host
#    debug:
#      var: hostvars[ groups['db'][0] ].ansible_default_ipv4
- name: Test Vars
  hosts: all
  vars:
    my_variable: hostvars[ groups['db'][0] ].ansible_default_ipv4
  tasks:
    - name: Print the value of my_variable
      debug:
        var: my_variable 


  
  