---
- hosts: db
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - role: xtradbCluster
      xtradb_databases:
        - name: morpheus
      xtradb_users:
        - name: morpheus
          password: PASSWD
          priv: 'morpheus.*:ALL,GRANT/*.*:SELECT,PROCESS,SHOW DATABASES,SUPER'