---
- include_tasks: morpheus_packages_ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: morpheus_configure.yml

- include_tasks: morpheus_check_elastic.yml

- debug:
    var: rabbitmq_sot_bind_address

- debug:
    var: rabbitmq_sot

- include_tasks: morpheus_rabbitmq_cluster.yml

#- include_tasks: morpheus_initial_setup.yml
#  when: morpheus_setup