--- 
- name: Check Elastic
  vars:
    monitor: 9300
    timeout: 5
  tasks:
    - wait_for:
        port: "{{ monitor }}"
        host: "{{ item }}"
        timeout: "{{ timeout }}"
        msg: "{{ item }} is not running. End of play."
      loop: "{{ groups['morph'] }}"