--- 
- name: ensure hostnames are in the host file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}"
  with_items: "{{ groups['morph'] }}"

- name: Morpheus UI | Push Morpheus config
  template:
    src: morph.config.j2
    dest: /etc/morpheus/morpheus.rb
  register: configpush

- name: Reconfigure hosts
  include_tasks: morpheus_run_reconfigure.yml
  when: ( morpheus_upgrade_flag == false )