---
- name: Update morpheus-secrets.json
  become: true
  replace:
    path: /etc/morpheus/morpheus-secrets.json
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  loop:
    - { regexp: '("cookie": )"[^"]+"', replace: '\\1"CD697E962C554A9EC2F1"' }
