---
- name: Add NFS mount to /etc/fstab
  lineinfile:
    dest: /etc/fstab
    line: "{{ morpheus_nfs }}:/ /var/opt/morpheus/morpheus-ui nfs defaults 0 0"

- name: Creates mount point
  file:
    path: /var/opt/morpheus/morpheus-ui
    state: directory

- name: Install nfs-common
  apt:
    name: nfs-common
    state: present
    
#- name: Mount NFS 
# mount:
#    src: "{{ morpheus_nfs }}:/"
#    path: "/var/opt/morpheus/morpheus-ui"
#    fstype: nfs
#    opts: defaults
#    dump: 0
#    passno: 0
#    state: mounted
