---
- name: Get first IP address of the host in the morph group. This will be our source of truth (SOT) node for RabbitMQ clustering
  set_fact:
    rabbitmq_sot_ip: "{{ groups['morph'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | list | sort | first}}"

- debug:
    var: rabbitmq_sot_ip

- debug:
    var: rabbitmq_sot_bind_address

- name: Create a file on each morpehus node and write the hostname to it
  block:
    - name: Touch file  
      file:
        path: /tmp/hostname
        state: touch
    
    - name: Write hostname to file
      lineinfile:
        path: /tmp/hostname
        line: "{{ ansible_hostname }}"

- name: Get the /tmp/hostname file from the SOT node and store it on the ansible server
  fetch:
    src: /tmp/hostname
    dest: /tmp/hostname
    flat: yes
  when:
    - rabbitmq_sot_bind_address == rabbitmq_sot_ip

- name: Set fact for the SOT hostname
  set_fact:
    rabbitmq_sot_host: "{{ lookup('file', '/tmp/hostname') }}"
    run_once: true

- debug:
    msg : "{{ rabbitmq_sot_host }}"
