--- 
- name: Sort hosts by IP address
  set_fact:
    sorted_hosts: "{{ groups['morph'] | sort(attribute='ansible_default_ipv4.address') }}"

- name: Get IP address and hostname of the first host
  debug:
    var: hostvars[first_host]['ansible_default_ipv4']['address']
    var: hostvars[first_host]['ansible_hostname']
  vars:
    first_host: "{{ sorted_hosts | first }}"
