--- 
- name: SOT IP Address
  set_fact:
    rabbitmq_sot_ip: "{{ hostvars[ groups['morph'][0] ].ansible_eth0.ipv4.address }}"

- debug:
    var: rabbitmq_sot_ip

- name: SOT hostname
  set_fact:
    rabbitmq_sot_host: "{{ hostvars[ groups['morph'][0] ].ansible_hostname }}"

- debug:
    var: rabbitmq_sot_host

#- name: Get first IP address of host in the morph group. This will be our SOT node for RabbitMQ clustering
#  set_fact:
#    rabbitmq_sot: "{{ groups['morph'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | list | sort | first}}"
#
#- debug:
#    var: rabbitmq_sot
#
#- name: Get hostname of the SOT node
#  set_fact:
#    rabbitmq_sot_name: "{{ ansible_hostname }}"
#  when: ansible_eth0.ipv4.address == "{{ rabbitmq_sot }}"
#
#- name: Write SOT hostname to a file
#  become: true
#  file:
#    path: /var/tmp/sot
#    state: touch
#  run_once: true
#  when: ansible_eth0.ipv4.address == "{{ rabbitmq_sot }}"
#
#- name: Write fact to file
#  lineinfile:
#    path: /var/tmp/sot
#    line: "{{ rabbitmq_sot_name }}"
#  when: ansible_eth0.ipv4.address == "{{ rabbitmq_sot }}"
#    