--- 
#- name: Sort hosts by IP address
#  set_fact:
#    sorted_hosts: "{{ groups['morph'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | sort }}"
#
#- name: Get hostname and IP address of the first host
#  debug:
#    msg: "Hostname: {{ hostvars[first_host]['ansible_hostname'] }}, IP Address: {{ hostvars[first_host]['ansible_default_ipv4']['address'] }}"
#  vars:
#    first_host: "{{ sorted_hosts | first }}"

- name: Set fact on every host
  set_fact:
    myvar: "{{ ansible_hostname }}"
  delegate_to: "{{ item }}"
  with_items: "{{ play_hosts }}"
  run_once: true

- debug:
    msg: "{{ myvar }}"

    