--- 
- name: check elastic
  wait_for:
    port: 9300
    host: "{{ item }}"
    timeout: 5
    msg: "{{ item }} is not running. End of play."
  loop: "{{ groups['morph'] }}"  

#- name: Print var
#  vars:
#    pete: jones
#  
#  tasks:
#    - name: Print variable
#      debug:
#        var: pete

#- name: Set RabbitMQ variables from config file
#  vars:
#    rabbitmq_config: "{{ lookup('file', '/etc/morpheus/morpheus-secrets.json') | from_json }}"
#    morpheus_password: "{{ rabbitmq_config.rabbitmq.morpheus_password }}"
#    queue_user_password: "{{ rabbitmq_config.rabbitmq.queue_user_password }}"
#    cookie: "{{ rabbitmq_config.rabbitmq.cookie }}"
#  delegate_to: "{{ groups[morph][0] }}"
#  run_once: true
#
#- name: Print RabbitMQ variables
#  debug:
#    vars:
#      cookie: "{{ cookie }}"
#      morpheus_password: "{{ morpheus_password }}"
#      queue_user_password: "{{ queue_user_password }}"

#- name: Update morpheus-secrets.json
#  become: true
#  replace:
#    path: /etc/morpheus/morpheus-secrets.json
#    regexp: '{{ item.regexp }}'
#    replace: '{{ item.replace }}'
#  loop:
#    - { regexp: '("morpheus_password": )"[^"]+"', replace: '"morpheus_password": "password",' }
#    - { regexp: '("queue_user_password": )"[^"]+"', replace: '"queue_user_password": "queuepassword",' }
#    - { regexp: '("cookie": )"[^"]+"', replace: '"cookie": "erlangcookie"' }