--- 
#- name: Get data
#  fetch:
#    src: /etc/morpheus/morpheus-secrets.json
#    dest: /tmp/morpheus-secrets.json
#    flat: yes
#  delegate_to: "{{ groups['morph'][0] }}"

- name: Set fact for morpheus_password
  set_fact:
    morpheus_password: "{{ lookup('file', '/tmp/morpheus-secrets.json') | from_json | json_query('rabbitmq.morpheus_password') }}"
  delegate_to: "{{ groups['morph'][0] }}"

- debug:
    msg : '{{ morpheus_password }}'

#- name: Set fact for RMQ SOT
#  set_fact:
#    pete: "jones"
#
#- debug:
#    msg : '{{ pete }}'

#- name: Set RabbitMQ variables from config file
#  set_fact:
#    rabbitmq_config: "{{ lookup('file', '/etc/morpheus/morpheus-secrets.json') | from_json }}"
#    morpheus_password: "{{ rabbitmq_config.rabbitmq.morpheus_password }}"
#    queue_user_password: "{{ rabbitmq_config.rabbitmq.queue_user_password }}"
#    cookie: "{{ rabbitmq_config.rabbitmq.cookie }}"
#  delegate_to: "{{ groups[morph][0] }}"
#  run_once: true
#
#- name: Print RabbitMQ variables
#  debug:
#    vars:
#      cookie: "{{ cookie }}"
#      morpheus_password: "{{ morpheus_password }}"
#      queue_user_password: "{{ queue_user_password }}"

#- name: Update morpheus-secrets.json
#  become: true
#  replace:
#    path: /etc/morpheus/morpheus-secrets.json
#    regexp: '{{ item.regexp }}'
#    replace: '{{ item.replace }}'
#  loop:
#    - { regexp: '("morpheus_password": )"[^"]+"', replace: '"morpheus_password": "password",' }
#    - { regexp: '("queue_user_password": )"[^"]+"', replace: '"queue_user_password": "queuepassword",' }
#    - { regexp: '("cookie": )"[^"]+"', replace: '"cookie": "erlangcookie"' }