---
- name: Create a file on node
  block:
    - name: Touch file  
      file:
        path: /tmp/pete1
        state: touch
#- include_tasks: morpheus_packages_ubuntu.yml
#  when: ansible_os_family == 'Debian'
#
#- include_tasks: morpheus_configure.yml
#
#- include_tasks: morpheus_check_elastic.yml
#
#- include_tasks: morpheus_rabbitmq_cluster.yml
#
#- include_tasks: morpheus_initial_setup.yml
#  when: morpheus_setup
